---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::LocationId
## it defines mappings from voyager.location_id column to Koha's shelving_location and branchcode
##

#Voyager.LOCATION -table
#location_id,location_code,       #location_name

#branchLoc sets the following attributes:
#       branchcode, shelving_location, collection_code, sub_location, item.itemtype, item.notforloan-status
1: branchLoc(Hamko, EI_KOHAAN, undef, undef) #Hamkoark, Evo Arkisto
2: branchLoc(Hamko, kir, undef, undef) #Hamkokir, Evo Kirjasto,translated values would be: branchcode=Hamko, location=kir, ccode=undef, sub_location=undef
3: branchLoc(Hamko, var) #Hamkovar, Evo Varasto,
4: branchLoc(Hamko, leh) #Hamkoleh, Evo Lehdet,
5: branchLoc(Hamko, EI_KOHAAN) #Hamkoopi, Evo Opinn?ytteet,
6: branchLoc(Hamkf, EI_KOHAAN) #Hamkfark, Forssa Arkisto,
7: branchLoc(Hamkf, kir) #Hamkfkir, Forssa Kirjasto,
8: branchLoc(Hamkf, EI_KOHAAN) #Hamkfref, Forssa K?sikirjasto
9: branchLoc(Hamkf, leh) #Hamkfleh, Forssa Lehdet,
10: branchLoc(Hamkf, EI_KOHAAN) #Hamkfopi, Forssa Opinn?ytteet,
11: branchLoc(Hamkf, EI_KOHAAN) #Hamkfstan, Forssa Standardit,
12: branchLoc(Hamka, kir) #Hamkavana, Visam?ki Kirjasto,
13: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkaahve,zz?L? K?YT?
14: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkaaula, zzEI K?YT?SS?,
15: branchLoc(Hamka, leh) #Hamkaleh, Visam?ki Lehdet,
16: branchLoc(Hamka, EI_KOHAAN) #Hamkakir, zzPOIS K?YT?ST?,
17: branchLoc(Hamkh, ref) #Hamkaref, Visam?ki K?sikirjasto,#uusi kirjasto KOHAssa Henkilökunnan kokoelma, Hamkh
18: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkasal, Visam?ki Salainen,
19: branchLoc(Hamka, ref) #Hamkasai, Sairio K?sikirjasto, # Visamäen käsikirjastoon?
20: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkaopi, Visam?ki Opinn?ytteet,
21: branchLoc(Hamka, stan) #Hamkastan, Visam?ki Standardit,
22: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkavar, Visam?ki Varasto,
23: branchLoc(Hamkl, kir) #Hamklkir, Lepaa Kirjasto,
24: branchLoc(Hamkl, ref) #Hamklref, Lepaa K?sikirjasto,
25: branchLoc(Hamkl, leh) #Hamklleh, Lepaa Lehdet,
26: branchLoc(Hamkl, EI_KOHAAN) #Hamklopi, Lepaa Opinn?ytteet,
27: branchLoc(Hamkl, var) #Hamklvar, Lepaa Varasto,
28: branchLoc(Hamkl, EI_KOHAAN) #Hamklstan, Lepaa Standardit,
29: branchLoc(Hamkl, mus, LIN, undef) #Hamklmhl, LepaaMuseo Hertta Linkola,#Kirjasto KOHAssa Mustilala, hyllypaikka_loc museo ja Ccode Hertta Linkolan kokoelma
30: branchLoc(Hamkl, mus) #Hamklmmus, LepaaMuseo Museokokoelma, 
31: branchLoc(Hamkm, ark) #Hamkmark, Mustiala Arkisto,
32: branchLoc(Hamkm, kir) #Hamkmkir, Mustiala Kirjasto,
33: branchLoc(Hamkm, var) #Hamkmvar, Mustiala Varasto,
34: branchLoc(Hamkm, EI_KOHAAN) #Hamkmref, Mustiala K?sikirjasto,
35: branchLoc(Hamkm, leh) #Hamkmleh, Mustiala Lehdet,
36: branchLoc(Hamkm, EI_KOHAAN) #Hamkmopi, Mustiala Opinn?ytteet,
37: branchLoc(Hamkr, ref) #Hamkrref, Riihim?ki K?sikirjasto,
38: branchLoc(Hamkr, kir) #Hamkrkir, Riihim?ki Kirjasto,
39: branchLoc(Hamkr, EI_KOHAAN) #Hamkrvar, Riihim?ki Varasto,
40: branchLoc(Hamkr, EI_KOHAAN) #Hamkrark, Riihim?ki Arkisto,
41: branchLoc(Hamkr, leh) #Hamkrleh, Riihim?ki Lehdet,
42: branchLoc(Hamkr, EI_KOHAAN) #Hamkropi, Riihim?ki Opinn?ytteet,
43: branchLoc(Hamkr, stan) #Hamkrstan, Riihim?ki Standardit,
44: branchLoc(Hamkr, EI_KOHAAN) #Hamkritse, XXRiihim?ki Itseopiskelu,
45: branchLoc(Hamkv, kir) #Hamkvkir, Valkeakoski Kirjasto,
46: branchLoc(Hamkv, ref) #Hamkvref, Valkeakoski K?sikirjasto,
47: branchLoc(Hamkv, leh) #Hamkvleh, Valkeakoski Lehdet,
48: branchLoc(Hamkv, EI_KOHAAN) #Hamkvopi, Valkeakoski Opinn?ytteet,
49: branchLoc(Hamkv, stan) #Hamkvstan, Valkeakoski Standardit,
50: branchLoc(Hamkv, EI_KOHAAN) #Hamkvark, Valkeakoski Arkisto,
51: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwkir, zzWetterhoff Kirjasto,
52: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwref, zzWetterhoff K?sikirjasto,
53: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwdia, xxWetterhoff Diat,
54: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwleh, zzWetterhoff Lehdet,
55: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwopi, zzWetterhoff Opinn?ytteet,
56: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwark, zzWetterhoff Arkisto,
57: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwstan, zzWetterhoff Standardit,
58: branchLoc(Hamko, EI_KOHAAN) #HAMKOLAINA, EVO LAINAUS,
59: branchLoc(Hamkf, EI_KOHAAN) #HAMKFLAINA, FORSSA LAINAUS,
60: branchLoc(Hamka, EI_KOHAAN) #HAMKALAINA, VISAM?KI LAINAUS,
61: branchLoc(Hamkl, EI_KOHAAN) #HAMKLLAINA, LEPAA LAINAUS,
62: branchLoc(Hamkm, EI_KOHAAN) #HAMKMLAINA, MUSTIALA LAINAUS,
63: branchLoc(Hamkr, EI_KOHAAN) #HAMKRLAINA, RIIHIM?KI LAINAUS,
64: branchLoc(Hamkv, EI_KOHAAN) #HAMKVLAINA, VALKEAKOSKI LAINAUS,
65: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKWLAINA, WETTERHOFF LAINAUS,
66: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKSELF, ITSEPALVELULAINAUS,
67: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKALUETT, HAMK LUETTELOINTI,
68: branchLoc(EI_KOHAAN, EI_KOHAAN) #TOIMLUETT, TOIMIPISTE LUETTELOINTI,
69: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKHANKI, HAMK HANKINTA,
70: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKOPAC, OPAC,
71: branchLoc(Hamko, EI_KOHAAN) #Hamkopois, Evo Poistot,
72: branchLoc(Hamkf, EI_KOHAAN) #Hamkfpois, Forssa Poistot,
73: branchLoc(Hamka, EI_KOHAAN) #Hamkapois, zzEI K?YTET?,
74: branchLoc(Hamkl, EI_KOHAAN) #Hamklpois, Lepaa Poistot,
75: branchLoc(Hamkm, EI_KOHAAN) #Hamkmpois, Mustiala Poistot,
76: branchLoc(Hamkr, EI_KOHAAN) #Hamkrpois, Riihim?ki Poistot,
77: branchLoc(Hamkv, EI_KOHAAN) #Hamkvpois, Valkeakoski Poistot,
78: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkwpois, Wetterhoff Poistot,
79: branchLoc(Hamka, EI_KOHAAN) #Hamkaraksa, Lahdensivu selvitett?vi?,
80: branchLoc(Hamko, EI_KOHAAN) #HAMKOSELF, EVO IP_LAINAUS,
81: branchLoc(Hamkf, EI_KOHAAN) #HAMKFSELF, FORSSA IP_LAINAUS,
82: branchLoc(Hamkl, EI_KOHAAN) #HAMKLSELF, LEPAA IP_LAINAUS,
83: branchLoc(Hamkm, EI_KOHAAN) #HAMKMSELF, MUSTIALA IP_LAINAUS,
84: branchLoc(Hamkr, EI_KOHAAN) #HAMKRSELF, RIIHIM?KI IP_LAINAUS,
85: branchLoc(Hamkv, EI_KOHAAN) #HAMKVSELF, VALKEAKOSKI IP_LAINAUS,
86: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKWSELF, WETTERHOFF IP_LAINAUS,
87: branchLoc(Hamko, ref) #Hamkoref, Evo K?sikirjasto,
88: branchLoc(Hamkh, vl) #Hamkvl, Virkak?ytt? - lainat, #uusi kirjasto KOHAssa Henkilökunnan kokoelma, Hamkh - hyllypaikka_location vl (virkalaina)
89: branchLoc(Hamkh, vs) #Hamkvs, Virkak?ytt? -sijainnit, #uusi kirjasto KOHAssa Henkilökunnan kokoelma, Hamkh ja hyllypaikka_location vs (virkasijainti)
90: branchLoc(Hamk, www) #Hamkwww, HAMK Verkkoaineisto,
91: branchLoc(Hamkl, EI_KOHAAN) #Hamklark, LepaaArkisto,
92: branchLoc(Hamkv, EI_KOHAAN) #Hamkvkurs, Valkeakoski kurssikirjat,
93: branchLoc(Hamkm, EI_KOHAAN) #Hamkmkurs, Mustiala kurssiaineisto,
94: branchLoc(Hamkl, EI_KOHAAN) #Hamklkurs, Lepaa kurssikirjat,
95: branchLoc(Hamkm, EI_KOHAAN) #Hamkmstan, Mustiala Standardit,
96: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkjulrek, HAMKin julkaisurekisteri,
97: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkbkir, XXLahdensivu Kirjasto,
99: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkbleh, XXLahdensivu Lehdet,
100: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkbopi, Lahdensivu Opinn?ytteet,
101: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKBLAINA, XXAINOLA-SOTE,
102: branchLoc(EI_KOHAAN, EI_KOHAAN) #HAMKBSELF, LAHDENSIVU IP_LAINAUS,
103: branchLoc(Hamka, EI_KOHAAN) #Hamkakurs, Visam?ki kurssikirjat,
104: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkbkurs, XXLahdensivu kurssiain,
105: branchLoc(Hamkr, EI_KOHAAN) #Hamkrkurs, Riihim?ki kurssikirjat,
106: branchLoc(Hamka, EI_KOHAAN) #Hamkalex, Visam?ki Sanomalehdet,
107: branchLoc(EI_KOHAAN, EI_KOHAAN) #Hamkblex, Lahdensivu Sanomalehdet,
108: branchLoc(Hamkf, EI_KOHAAN) #Hamkflex, Forssa Sanomalehdet,
109: branchLoc(Hamkl, EI_KOHAAN) #Hamkllex, Lepaa Sanomalehdet,
110: branchLoc(Hamkm, EI_KOHAAN) #Hamkmlex, Mustiala Sanomalehdet,
111: branchLoc(Hamko, EI_KOHAAN) #Hamkolex, Evo Sanomalehdet,
112: branchLoc(Hamkr, EI_KOHAAN) #Hamkrlex, Riihim?ki Sanomalehdet,
113: branchLoc(Hamkv, EI_KOHAAN) #Hamkvlex, Valkeakoski Sanomalehdet,
114: branchLoc(Hamkm, mus) #Hamkmmus, Mustiala Museokokoelma
115: branchLoc(Hamkv, EI_KOHAAN) #Hamkvvar, Valkeakoski Varasto,
116: branchLoc(Hamka, EI_KOHAAN) #Hamkoesi, Evo Esineet,
117: branchLoc(Hamk, ark) #Hamksark, HAMK Opinn?ytety?arkisto,
118: branchLoc(Hamk, wwwn) #Hamkwwwn, Tietokannat Vanaicatissa,
119: branchLoc(Hamko, mus) #Hamkomus, Evo Museo, #Uusi museokokoelma kirjastona
120: branchLoc(EI_KOHAAN, EI_KOHAAN) #MAKSU, Verkkomaksaminen,
_DEFAULT_: branchLoc(Hamk, KONVERSIO, ERROR, ERROR) #By default, print a warning and use defaults )
