---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::NoteType
## it defines mappings from voyager.note_type integer to plain text descriptions, prepended to Koha's notes-fields
##

1:       General
2:       Address
3:       Barcode
4:       Phone
5:       popUp()              # Pop-Up, handle special logic in a separate function.
6:       Universal Borrowing
