---

##
## IN THIS FILE
##
## The main configurations for MMT Voyager
##
##
## Configurations are introduced in the same order as they are needed by the migration tools

# From which system are we migrating from?
# One of ['Voyager', 'PrettyLib']
sourceSystemType: 'Voyager'

############################
### 1) Data export phase ###
## Voyager DB dumps are fetched and delivered for the data transformation phase

# Name of the script in directory $MMT_HOME/secret used to extract data from the VoyagerDB-server into the Koha-server.
# See the extractor-dir for example implementations.
exportPipelineScript: 'voyagerToTransformer.sh'

####################################
### 2) Data transformation phase ###
## Exported DB rows are mangled into Koha-objects

# Anonymize Borrower records?
anonymize: 1

# Enable multithreading by defining workers.
workers: 0

# Load ssns to Hetula instead of storing them in Koha as plain text.
# Boolean value
useHetula: false

# Holdings transformation strategy to use.
# The way holdings records are used in various databases vary, hence one transformation set of rules wont work for all source databases.
holdingsTransformationModule: HAMK

# If the item doesn't have a price or a replacementprice, use this default.
defaultReplacementPrice: 25

# ISIL-code for the migrated organization
# Used primarily in the MARC record transformations.
organizationISILCode: FI-Hamk

# Set the Patron home library to this value for all patrons. Leave empty to use the LocationId-translation table.
patronHomeLibrary:

# How many expiry years to add for patron account if expiry date is not defined in Voyager
patronAddExpiryYears: 0

# Which strategy to use to validate phone numbers
# See MMT::Validator::Phone for available strategies
phoneNumberValidationStrategy: HAMK

# How to deal with missing barcodes?
# ERROR: Barcodes must exist, mocks a barcode based on the Id
# IGNORE: Barcodes might be missing
# CREATE: Barcodes must exist. Creates a barcode using the pattern 'emptyBarcodePattern'
emptyBarcodePolicy: IGNORE

# Replaces zeroes (0) with the id of the object being transformed
emptyBarcodePattern: HAMK00000000

#############################
### 3) Data loading phase ###
## Exported DB rows are mangled into Koha-objects

# Name of the script in directory $MMT_HOME/secret used to import the transformed data into Koha
# See the importer-dir for example implementations.
importPipelineScript: 'transformerToKoha.sh'
