---

##
## IN THIS FILE
##
## The main configurations for MMT Voyager
##
##
## Configurations are introduced in the same order as they are needed by the migration tools

### 1) Data export phase
## Voyager DB dumps are fetched and delivered for the data transformation phase

# Absolute/full path to the script used to extract data from the VoyagerDB-server into the Koha-server.
# See the extractor-dir for example implementations.
exportPipelineScript: ''

# Absolute path to the script used to import the transformed data into Koha
# See the importer-dir for example implementations.
importPipelineScript: ''

# From where the files exported from Voyager are found?
voyagerExportDir: ''

### 2) Data transformation phase
## Exported DB rows are mangled into Koha-objects

# Where the built library system objects are stored to be transported to Koha?
kohaImportDir: ''

# Enable multithreading by defining workers.
workers: 0
