---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::ItemTypes
## it defines mappings from PrettyLib.Title.TitleType to koha.items.itype
##

#PrettyLib.Title.TitleType, koha.items.itype

#0:  KI # Kirja
0: KI
#1:  CD # CD-levy
1: CD
#2:  NU # Nuotti
2: NU
#3:  KA # Kausijulkaisu
3: KA
#4:  RA # Raportti
4: RA
#5:  VI # Videotallenne
5: VI
#6:  DI # Dia
6: DI
#7:  AR # Artikkeli
7: AR
#8:  ES # Esine
8: ES
#9:  OP # Opinnäytetyö
9: OP
#10: AT # ATK-tallenne
10: AT
#11: KO # Kokousjulkaisu
11: KO
#12: ST # Standardi
12: ST
#13: KR # Kartta
13: KR
#14: PA # Patentti
14: PA
#15: TU # Tutkimus
15: TU
#16: SO # Sopimus
16: SO
#17: MA # Määräys
17: MA
#18: PI # Pistekirjoitus
18: PI
#19: IS # Iso tekstinen
19: IS
#20: AA # Äänikirja
20: AA
#21: KV # Kalvot
21: KV
#23: TK # Tuotekansio
23: TK
#24: VA # Valokuva
24: VA
#25: OM # Oppimateriaali
25: OM
#26: EA # Elektroninen aineisto
26: EA
#27: MM # Multimedia
27: MM
#28: VK # Vuosikertomus
28: VK
#29: PP # Pienpainate
29: PP
#30: MO # Moniste
30: MO
#31: TI # Tilastojulkaisu
31: TI
#32: SA # Sarjajulkaisu
32: SA
#33: KM # Konemanuuali
33: KM
#34: EK # E-Kirja
34: EK

_DEFAULT_: warning()
